<?php

namespace ContainerXEDrLx6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_ZxR5LZFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.ZxR5LZF' shared service.
     *
     * @return \App\Repository\CampaignRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\CampaignController::index()": the $campaignRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CampaignRepository".');
    }
}
