<?php

namespace ContainerXEDrLx6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GjUQ_ZIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GjUQ.zI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GjUQ.zI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campaignRepository' => ['privates', '.errored.ZxR5LZF', NULL, 'Cannot determine controller argument for "App\\Controller\\CampaignController::index()": the $campaignRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CampaignRepository".'],
        ], [
            'campaignRepository' => '?',
        ]);
    }
}
