<?php

namespace ContainerXEDrLx6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.epKkOAk.App\Entity\Campaign' shared service.
     *
     * @return \App\Entity\Campaign
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.epKkOAk": it references class "App\\Entity\\Campaign" but no such service exists.');
    }
}
