<?php

namespace ContainerE9puQi3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ui214X2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ui214X2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ui214X2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participant' => ['privates', '.errored..service_locator.Ui214X2.App\\Entity\\Participant', NULL, 'Cannot autowire service ".service_locator.Ui214X2": it references class "App\\Entity\\Participant" but no such service exists.'],
        ], [
            'participant' => 'App\\Entity\\Participant',
        ]);
    }
}
