<?php

namespace ContainerE9puQi3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WH6ui5rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WH6ui5r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WH6ui5r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CampaignController::delete' => ['privates', '.service_locator.o6KmXmP', 'get_ServiceLocator_O6KmXmPService', true],
            'App\\Controller\\CampaignController::edit' => ['privates', '.service_locator.o6KmXmP', 'get_ServiceLocator_O6KmXmPService', true],
            'App\\Controller\\CampaignController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CampaignController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CampaignController::show' => ['privates', '.service_locator.epKkOAk', 'get_ServiceLocator_EpKkOAkService', true],
            'App\\Controller\\ParticipantController::delete' => ['privates', '.service_locator.i6M4c8P', 'get_ServiceLocator_I6M4c8PService', true],
            'App\\Controller\\ParticipantController::edit' => ['privates', '.service_locator.i6M4c8P', 'get_ServiceLocator_I6M4c8PService', true],
            'App\\Controller\\ParticipantController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ParticipantController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ParticipantController::show' => ['privates', '.service_locator.Ui214X2', 'get_ServiceLocator_Ui214X2Service', true],
            'App\\Controller\\PaymentController::delete' => ['privates', '.service_locator.ADzfUK5', 'get_ServiceLocator_ADzfUK5Service', true],
            'App\\Controller\\PaymentController::edit' => ['privates', '.service_locator.ADzfUK5', 'get_ServiceLocator_ADzfUK5Service', true],
            'App\\Controller\\PaymentController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PaymentController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PaymentController::show' => ['privates', '.service_locator.tPSEDJD', 'get_ServiceLocator_TPSEDJDService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CampaignController:delete' => ['privates', '.service_locator.o6KmXmP', 'get_ServiceLocator_O6KmXmPService', true],
            'App\\Controller\\CampaignController:edit' => ['privates', '.service_locator.o6KmXmP', 'get_ServiceLocator_O6KmXmPService', true],
            'App\\Controller\\CampaignController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CampaignController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CampaignController:show' => ['privates', '.service_locator.epKkOAk', 'get_ServiceLocator_EpKkOAkService', true],
            'App\\Controller\\ParticipantController:delete' => ['privates', '.service_locator.i6M4c8P', 'get_ServiceLocator_I6M4c8PService', true],
            'App\\Controller\\ParticipantController:edit' => ['privates', '.service_locator.i6M4c8P', 'get_ServiceLocator_I6M4c8PService', true],
            'App\\Controller\\ParticipantController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ParticipantController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ParticipantController:show' => ['privates', '.service_locator.Ui214X2', 'get_ServiceLocator_Ui214X2Service', true],
            'App\\Controller\\PaymentController:delete' => ['privates', '.service_locator.ADzfUK5', 'get_ServiceLocator_ADzfUK5Service', true],
            'App\\Controller\\PaymentController:edit' => ['privates', '.service_locator.ADzfUK5', 'get_ServiceLocator_ADzfUK5Service', true],
            'App\\Controller\\PaymentController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PaymentController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PaymentController:show' => ['privates', '.service_locator.tPSEDJD', 'get_ServiceLocator_TPSEDJDService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CampaignController::delete' => '?',
            'App\\Controller\\CampaignController::edit' => '?',
            'App\\Controller\\CampaignController::index' => '?',
            'App\\Controller\\CampaignController::new' => '?',
            'App\\Controller\\CampaignController::show' => '?',
            'App\\Controller\\ParticipantController::delete' => '?',
            'App\\Controller\\ParticipantController::edit' => '?',
            'App\\Controller\\ParticipantController::index' => '?',
            'App\\Controller\\ParticipantController::new' => '?',
            'App\\Controller\\ParticipantController::show' => '?',
            'App\\Controller\\PaymentController::delete' => '?',
            'App\\Controller\\PaymentController::edit' => '?',
            'App\\Controller\\PaymentController::index' => '?',
            'App\\Controller\\PaymentController::new' => '?',
            'App\\Controller\\PaymentController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CampaignController:delete' => '?',
            'App\\Controller\\CampaignController:edit' => '?',
            'App\\Controller\\CampaignController:index' => '?',
            'App\\Controller\\CampaignController:new' => '?',
            'App\\Controller\\CampaignController:show' => '?',
            'App\\Controller\\ParticipantController:delete' => '?',
            'App\\Controller\\ParticipantController:edit' => '?',
            'App\\Controller\\ParticipantController:index' => '?',
            'App\\Controller\\ParticipantController:new' => '?',
            'App\\Controller\\ParticipantController:show' => '?',
            'App\\Controller\\PaymentController:delete' => '?',
            'App\\Controller\\PaymentController:edit' => '?',
            'App\\Controller\\PaymentController:index' => '?',
            'App\\Controller\\PaymentController:new' => '?',
            'App\\Controller\\PaymentController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
