<?php

namespace ContainerE9puQi3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaign2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o6KmXmP.App\Entity\Campaign' shared service.
     *
     * @return \App\Entity\Campaign
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.o6KmXmP": it references class "App\\Entity\\Campaign" but no such service exists.');
    }
}
