<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9puQi3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9puQi3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE9puQi3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE9puQi3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE9puQi3\App_KernelDevDebugContainer([
    'container.build_hash' => 'E9puQi3',
    'container.build_id' => 'cb709330',
    'container.build_time' => 1649941400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9puQi3');
